language: node_js

node_js:
  - '8'

branchs:
  only:
  - master

env:
  - CXX=g++-4.8
  global:
  - GT_REF: git@gitee.com:owlaford/halo.git

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - 'node_modules'

script:
  - npm run unit
  - npm run lint
  - npm run build

