language: node_js

node_js:
  - '8'

branchs:
  only:
  - master

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - 'node_modules'

script:
  - npm run unit
  - npm run lint
  - npm run build

after_script:
  - cd ./dist
  - git config --global user.name "owlaford"
  - git config --global user.email "244734834@qq.com"
  - git init
  - git add .
  - git commit -m "update"
  - git remote add origin https://owlaford:${GT_PASSWORD}@gitee.com/owlaford/halo.git
  - git push -f origin master